---
title: "lab3"
author: "stella zhou"
format: 
  html:
    embed-resources: true
editor: visual
---

## 1. Read in the data

```{r}

met <- data.table::fread(file.path("~", "Downloads", "met_all.gz"))
```

## 2. Check dimension, headers, footers

```{r}
dim(met)
```

```{r}
head(met)
```

```{r}

tail(met)
```

## 3. check variables

```{r}
str(met)
```

```{r}
summary(met[,8:13])
```

## 4. look closer

```{r}
table(met$year)
```

```{r}
table(met$day)
```

```{r}
table(met$hour)
```

```{r}
summary(met$temp)
```

-40 is too low for summer ==\> missing value

```{r}
summary(met$wind.sp)
```

```{r}
summary(met$elev)
```

max elev = 9999 --\> there is missing data. replace 9999 with NA.

```{r}
met[met$elev==9999.0] <- NA

```

```{r}
summary(met$elev)
```

```{r}
mean(is.na(met$elev))
```

==\> tells the proportion that is N/A, 2.5% of the data are missing

```{r}
summary(met$elev)
```

```{r}
summary(met$wind.sp)
```

Remove temperature that's -40

```{r}
met <- met[temp>-40]
met2 <- met[order(temp)]
head(met2)
```

### **5. Check the data against an external data source.**

```{r}
met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)
```

### **6. Calculate summary statistics**

```{r}
elev <- met[elev==max(elev), ]
summary(elev)
```

```{r}
cor(elev$temp, elev$wind.sp, use="complete")
```

```{r}
cor(elev$temp, elev$hour, use="complete")
```

```{r}
cor(elev$wind.sp, elev$day, use="complete")
```

```{r}
cor(elev$wind.sp, elev$hour, use="complete")
```

```{r}
cor(elev$temp, elev$day, use="complete")
```

### **7. Exploratory graphs**

```{r}
hist(met$elev, breaks=100)
```

```{r}
hist(met$temp)
```

```{r}
hist(met$wind.sp)
```

```{r}
library(leaflet)
leaflet(elev) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)
```

```{r}
library(lubridate)
elev$date <- with(elev, ymd_h(paste(year, month, day, hour, sep= ' ')))
summary(elev$date)
```

```{r}
elev <- elev[order(date)]
head(elev)
```

```{r}
plot(elev$date, elev$temp, type='l')
```

```{r}
plot(elev$date, elev$wind.sp, type='l')
```
